### ISSUE TITLE
Pick up and carry physics objects in a 2D platformer

### ISSUE THREAD

**Issue by 16018389** [PlaceholderGames/1stYearHelpDesk#14]
Has anyone managed to set this up or find a good tutorial on setting it up? I've been pulling my hair out trying to get it to work but every tutorial I've found are designed for 3D games and I haven't been able to tweak any of them to work for a 2D platformer.

**Comment by DoctorMikeReddy** [comment]
Has this been sorted now?

**Comment by 16018389** [comment]
Yes, we figured out an alternative that involves spawning the blocks instead of carrying them.

**Comment by DoctorMikeReddy** [comment]
Clever. Neat way to avoid the problem
