### ISSUE TITLE
How do I change levels in Unreal

### ISSUE THREAD

**Issue by DoctorMikeReddy** [PlaceholderGames/1stYearHelpDesk#2]
Although this video tutorial is set in a 3D game, the creation of a trigger box and the blueprint for transitioning to a new level (or map) is identical for Paper 2D. If you have any questions, just ask:
https://www.youtube.com/watch?v=FcMeHSGiYaA

**Comment by DoctorMikeReddy** [comment]
Asked in a self-study session, but likely that many of you will want to swap between levels in your games.

**Comment by DoctorMikeReddy** [comment]
Another one:
https://www.youtube.com/watch?v=N_q8jTs8gU0

**Comment by DoctorMikeReddy** [comment]
A much more advanced tutorial on level streaming, which won't be necessary for a Paper2D game:
https://docs.unrealengine.com/latest/INT/Engine/LevelStreaming/HowTo/StreamWithBlueprints/

**Comment by kayloshai** [comment]
Pretty good tutorial videos @DoctorMikeReddy, thanks a lot :)
