### ISSUE TITLE
how to create a tracking camera from scratch?

### ISSUE THREAD

**Issue by GryffDerrick** [PlaceholderGames/1stYearHelpDesk#22]
We created a character blueprint from scratch and are having issues getting a camera to track the player.

**Comment by 16018389** [comment]
Have you tried attaching a camera boom to the player and then a camera to the camera boom? The camera will be attached to the player though

**Comment by GryffDerrick** [comment]
Yeah we've done that, the issue was the camera was colliding. We've fixed
it now.

**Comment by DoctorMikeReddy** [comment]
A little detail on how you fixed it might be helpful
