### ISSUE TITLE
How do I put a background image in my main menu?

### ISSUE THREAD

**Issue by DoctorMikeReddy** [PlaceholderGames/1stYearHelpDesk#33]
Sam asked this. Here is a tutorial that helps:
https://forums.unrealengine.com/development-discussion/content-creation/36095-how-can-i-put-a-background-in-my-main-menu

**Comment by chrisington** [comment]
I found this video quite useful for creating a basic menu as well:

https://www.youtube.com/watch?v=sqyTJ_xXwkI
