### ISSUE TITLE
Image quality loss when exporting image from affinity designer

### ISSUE THREAD

**Issue by DamionMorgan** [PlaceholderGames/1stYearHelpDesk#38]
I'm working on a tileset using affinity designer (I guess it's a bit like photoshop or something idk) - and I have a tile with some smooth curves and edges. 
I'm struggling to export this image without losing the quality of it in the process.

I can't export as a JPEG because it doesn't seem to support transparant backgrounds.
I've been going through the different export settings for PNG with trial and error, none have yielded desirable results. 
The options are -
Nearest Neighbour, bilinear, bicubic, lanczos 3 seperable, lanczos 3 non-seperable.

The image is 128px by 128px, that's how big I intend the tiles to be.

Any help would be appreciated, but I don't expect much because this seems to be a really vague and uninteresting problem.
Might just have to settle for a blurry game.

**Comment by DoctorMikeReddy** [comment]
128 x 128 seems quite large for tiles. Usually, they are 32x32 or so, although there are some variations, of course. Sounds like you are working with an image that is too big, if you are losing quality when exporting. Are you changing the size in the process? This is usually the reason for degradation. PNG is the way to go, but can you post before/after images, so I can get an idea of what you are experiencing, please?

**Comment by DamionMorgan** [comment]
Turns out the issue wasn't as bad as I was making it out to be. I think most of it came down to not applying Paper 2D texture settings.
The tileset is a work in progress, not too comfortable sharing it yet for autistic reasons D;
