### ISSUE TITLE
Midi tracks/SVGs for UE4 (non-compatible file types made compatible?)

### ISSUE THREAD

**Issue by DamionMorgan** [PlaceholderGames/1stYearHelpDesk#46]
I've got some midi soundtracks I'd like to use for the game I'm working on. 
Unreal Engine doesn't support midi.
There's a plugin for an older version of UE4 that allows midi, doesn't work for the engine version we're using.
When converting midi to wav, the song ends up sounding completely different and just not really ideal.

Any advice?

If it comes down to it, I'll settle for the crappy wav versions, but I'd like to explore some more options first.

On the topic of UE4 not supporting certain files, anyone know how to get SVGs to work? The rasterizing of images that PNG causes is a bit sucky for my vector based graphics.

**Comment by DoctorMikeReddy** [comment]
Use Audacity to convert Midi to Wav. SVGs should be exported to a raster format at the right size, to best reduce conversion effects
