### ISSUE TITLE
Making an object transparent

### ISSUE THREAD

**Issue by Maxpower97** [PlaceholderGames/1stYearHelpDesk#49]
I'm making a light ball for our game and I want to try and make it transparent. Does anyone know where I can find a tutorial that'll allow me to do that please.

**Comment by DoctorMikeReddy** [comment]
Have you sorted this yet? If not, applying a transparent texture, or choosing not to render the object in UE4 might be the way forward.

**Comment by chrisington** [comment]
If anyone is still stuck with this, I found this video very useful (Transparency information starts around 8:35) : https://youtu.be/v1n8imay2Tg?t=514
