### ISSUE TITLE
Git Bash Guide (Uploading/ Dowloading Projects From GitHub and Creating Branches)

### ISSUE THREAD

**Issue by chrisington** [PlaceholderGames/1stYearHelpDesk#52]
I found Git Bash a little hard to get used to. As Mike has had to explain this program multiple times to me, I thought I would share my notes here so people that still haven't used it have something to reference to.

Git Bash is capable of uploading and downloading branches from your repository so that you and your team can make changes to your project without deleting/ editing over each others content. The master branch will hold the most up-to-date version of your project and it's best to make branches for every other member of your team. 

It is important to note that you should always check that your combined projects work in Unreal before uploading them to GitHub. Sometimes, errors can occur when you try to merge projects and it's best to iron out these bugs before uploading. 

Your repository shouldn't really be any larger than 1gb, quite often the starter content offered by Unreal can take up a lot of space. Many of these files can be deleted if your team isn't using any of them. 

 Finally, Git Bash will sometimes make a habit of asking for your username and password over and over. Mike has already created an issue for stopping this problem: https://github.com/PlaceholderGames/1stYearHelpDesk/issues/47

Right click your project folder and click Git Bash here:
![image](https://user-images.githubusercontent.com/43669785/53565371-37703100-3b51-11e9-8be6-5b59c62acc2f.png)

Command pwd will let you show which local directory you are currently in: 
![image](https://user-images.githubusercontent.com/43669785/53565481-8ae27f00-3b51-11e9-8259-4c65a096533f.png)

Command **git clone** https://github.com/YOUR-REPOSITORY **.git** will clone a copy of the master branch of your repository which creates a folder of the same name in your selected local directory. You will be promoted to login with your username and password: 
![image](https://user-images.githubusercontent.com/43669785/53565678-ffb5b900-3b51-11e9-8e8d-0d0cb7168124.png)

If you've signed in correctly the program will begin cloning a copy of the directory to your locally selected folder, if not you may have entered your login details incorrectly: 
![image](https://user-images.githubusercontent.com/43669785/53566487-37bdfb80-3b54-11e9-80d6-e0b5406e0de0.png)

Check your local machine to make sure the folder has transferred over correctly:
![image](https://user-images.githubusercontent.com/43669785/53687552-e1a4b000-3d2d-11e9-8fdb-6191cd3043a8.png)

In my example repository, there is only one readme file:
![image](https://user-images.githubusercontent.com/43669785/53566384-e9a8f800-3b53-11e9-8f72-37ed9cf730e4.png)

In your Game repositories there should be a file called .gitignore. This file tells GitHub which files do not need to be updated from your Unreal Project:
![image](https://user-images.githubusercontent.com/43669785/53566571-7784e300-3b54-11e9-8e6a-6ab59c8ff4da.png)

Command cd your-repository-name/ will change directory in Git Bash to your master branch:
![image](https://user-images.githubusercontent.com/43669785/53567074-05ad9900-3b56-11e9-8c59-dc1e4044e00f.png)

In my local folder I have added a new text file: 
![image](https://user-images.githubusercontent.com/43669785/53567130-31308380-3b56-11e9-9831-eaaf1bcf989b.png)

Command git status has spotted this new file, and has red text to show it has not yet been uploaded to my repository:
![image](https://user-images.githubusercontent.com/43669785/53567162-44dbea00-3b56-11e9-8eaf-d0921e0ede68.png)

Command git branch NAMEOFBRANCH will create a new branch:
![image](https://user-images.githubusercontent.com/43669785/53567483-422dc480-3b57-11e9-99aa-7e04790d654c.png)

Command git checkout NAMEOFBRANCH will change the branch you want to upload changes to (You can see this change in blue text):
![image](https://user-images.githubusercontent.com/43669785/53567731-09421f80-3b58-11e9-82d0-fb3a9f97c7c1.png)

Command git add . will tell the program that you want to commit changes to the folder (the one's that were in red):
![image](https://user-images.githubusercontent.com/43669785/53687868-22062d00-3d32-11e9-8416-8fbc55c3bea3.png)

Now when I use the command git status, you can see all changes are now green instead of red:
![image](https://user-images.githubusercontent.com/43669785/53687881-6eea0380-3d32-11e9-886a-d2ddd26e11b0.png)

command git commit -m "Comments go here" will commit all changes you have told the program to make on the specified branch, the text in the comment should explain what changes you made when you uploaded this:
![image](https://user-images.githubusercontent.com/43669785/53687893-b3759f00-3d32-11e9-9461-a36acc0108b6.png)

Finally, command git push origin NAMEOFBRANCH will upload these changes to your repository branch:
![image](https://user-images.githubusercontent.com/43669785/53687935-5dedc200-3d33-11e9-9424-29b39ab5bc6d.png)

Now, when I refresh my repository in GitHub and click the drop down box Branch: master, it should show me my newly created branch: 
![image](https://user-images.githubusercontent.com/43669785/53687951-968d9b80-3d33-11e9-9b73-0fafcb791491.png)

The file I have added appears in this branch along with the comment I made using Git Bash:
![image](https://user-images.githubusercontent.com/43669785/53687961-aefdb600-3d33-11e9-9252-3437a90e8234.png)

Just as another example, I deleted this file from my computer and used Git Bash to reflect these changes in my example repository: 
![image](https://user-images.githubusercontent.com/43669785/53688009-afe31780-3d34-11e9-89c4-15e19a9b9c8f.png)
![image](https://user-images.githubusercontent.com/43669785/53688023-ede03b80-3d34-11e9-9f9f-c0c35fecd308.png)
![image](https://user-images.githubusercontent.com/43669785/53688015-cab58c00-3d34-11e9-945c-56fcbc03bd3f.png)
![image](https://user-images.githubusercontent.com/43669785/53688025-051f2900-3d35-11e9-8c0c-815e559c98bb.png)

**Comment by DoctorMikeReddy** [comment]
This is great. ‘git pull’ (origin BRANCH) and ‘git fetch’ are two other useful commands, when/if ‘git status’ show that the remote (online) copy is more up-to-date than the local copy. You mention merges too. Maybe a sequel to this guide?
