### ISSUE TITLE
Creating a main menu

### ISSUE THREAD

**Issue by sulky-penguin** [PlaceholderGames/1stYearHelpDesk#6]
If anyone is looking to find out how to create the main menu, this video has a great guide, including free assets if you want them.
Link: https://www.youtube.com/watch?v=SPzjL-j4Aas

**Comment by CometGoat** [comment]
Nice! It's important to note that using a heirarchy in your widgets is a lifesaver when you play your game on different size screens :)

**Comment by 16018389** [comment]
Definitely, it's really easy to get lost when your graphs are all over the place.
